### ISSUE TITLE
One more plot for generate-novolc-forcing.ipynb?

### ISSUE THREAD

**Issue by mnlevy1981** [matt-long/pinatubo-LE#1]
The `generate-novolc-forcing.ipynb` notebook looks great. I was thinking it might make sense to reproduce the plot from `Out[4]`(spanning the entire 1850 - 2008 time period) from the new dataset just to verify the only difference is in the 1991 - 1995 period.

I admit this might be a little over-cautious. The plot from cell 7 is certainly encouraging, and reading through the code I have no reason to suspect anything funny outside of the time period plotted.

**Comment by matt-long** [comment]
Good idea. I just pushed a commit that includes this plot. I also found that mysteriously the original dataset was getting modified, perhaps due to a switch between using `.data` and `.values` when replacing the Pinatubo period. I changed to the following (`deep=True`) in my copy and that fixed the problem.

```python
dso = ds.copy(deep=True)
```
